"""add club url

Revision ID: 84c7d2033aac
Revises: 223156b7ce49
Create Date: 2026-06-17 15:04:17.247579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c7d2033aac'
down_revision: Union[str, Sequence[str], None] = '223156b7ce49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'url')
    # ### end Alembic commands ###
