"""add advanced metrics

Revision ID: a111e3d36a69
Revises: c3399326ab66
Create Date: 2026-06-24 13:24:34.232167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a111e3d36a69'
down_revision: Union[str, Sequence[str], None] = 'c3399326ab66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player_stats', sa.Column('goals_per_90', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('assists_per_90', sa.Float(), nullable=True))
    op.add_column('player_stats', sa.Column('goal_contribution_per_90', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player_stats', 'goal_contribution_per_90')
    op.drop_column('player_stats', 'assists_per_90')
    op.drop_column('player_stats', 'goals_per_90')
    # ### end Alembic commands ###
