"""advanced_player_metrics

Revision ID: c3399326ab66
Revises: 90e4b8aad32f
Create Date: 2026-06-23 20:30:09.372595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3399326ab66'
down_revision: Union[str, Sequence[str], None] = '90e4b8aad32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('player_stats_unique'), 'player_stats', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('player_stats_unique'), 'player_stats', ['player_id', 'season', 'competition'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
